---
version: "3"
services:
  web:
    build: .
    hostname: myapp.com
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      service-network:
        ipv4_address: 192.168.92.20
  db:
    image: postgres:latest
    networks:
      service-network:
        ipv4_address: 192.168.92.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456wgh
      POSTGRES_DB: maridb
networks:
  service-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.92.0/24
